version = "1.0"

[metadata]
uthor_name = "Manas Agarwal"
author_email = "manasagarwal12921@gmail.com"
difficulty = "easy"
category = "system-administration"
tags = ["data-transform", "linux"]

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[solution.env]
